set_property PACKAGE_PIN Y18 [get_ports spi_ss_io]
set_property PACKAGE_PIN Y19 [get_ports spi_io1_io]
set_property PACKAGE_PIN Y16 [get_ports spi_io0_io]
set_property PACKAGE_PIN Y17 [get_ports spi_sck_io]

set_property IOSTANDARD LVCMOS33 [get_ports spi_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_sck_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_ss_io]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_txd]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_tri_o[0]}]
set_property PACKAGE_PIN W14 [get_ports {GPIO_0_tri_o[2]}]
set_property PACKAGE_PIN T10 [get_ports {GPIO_0_tri_o[1]}]
set_property PACKAGE_PIN V7 [get_ports {GPIO_0_tri_o[0]}]
set_property PACKAGE_PIN T11 [get_ports uart_rtl_rxd]
set_property PACKAGE_PIN Y14 [get_ports uart_rtl_txd]
