set_property SRC_FILE_INFO {cfile:C:/Vivado/SoC_2023/PE/Vraag3_2/Vraag3_2.srcs/constrs_1/new/Vraag3_XDC.xdc rfile:../../../Vraag3_2.srcs/constrs_1/new/Vraag3_XDC.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports {arduino_ar0_ar13_tri_io[10]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W9 [get_ports {GPIO_0_tri_io[0]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports {GPIO_0_tri_io[1]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A20 [get_ports {GPIO_0_tri_io[2]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports {GPIO_0_tri_io[3]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B20 [get_ports {GPIO_0_tri_io[4]}]
