set_property SRC_FILE_INFO {cfile:C:/Vivado/SoC_2023/PE/Vraag1/Vraag1.srcs/constrs_1/new/Vraag1.xdc rfile:../../../Vraag1.srcs/constrs_1/new/Vraag1.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports spi_ss_io]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y19 [get_ports spi_io1_io]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports spi_io0_io]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17 [get_ports spi_sck_io]
