set_property IOSTANDARD LVCMOS33 [get_ports d_out_0]
set_property PACKAGE_PIN W14 [get_ports d_out_0]
set_property PACKAGE_PIN Y18 [get_ports {gpo_I2C_RST[0]}]
set_property PACKAGE_PIN Y16 [get_ports IIC_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports {gpo_I2C_RST[0]}]
set_property PACKAGE_PIN Y17 [get_ports IIC_0_sda_io]

set_property IOSTANDARD LVCMOS33 [get_ports clk_in1_0]
set_property PACKAGE_PIN H16 [get_ports clk_in1_0]
